---
# Copyright (C) 2018-2022 Robert Wimmer
# SPDX-License-Identifier: GPL-3.0-or-later

- name: Restart wireguard
  ansible.builtin.service:
    name: "wg-quick@wg0"
    state: "{{ item }}"
  loop:
    - stopped
    - started
  listen: "restart wireguard"
